####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX Announcement
http:
  routers:
    local_announcement_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/announcement/`)"
      service: local_announcement
      middlewares:
        - local_announcement

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_announcement:
      stripPrefix:
        prefixes:
          - "/mfe/announcement"

  services:
    local_announcement:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5024/"   # Angular project started outside Docker with this port
