####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX Help
http:
  routers:
    local_help_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/help/`)"
      service: local_help
      middlewares:
        - local_help

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_help:
      stripPrefix:
        prefixes:
          - "/mfe/help"

  services:
    local_help:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5023/"   # Angular project started outside Docker with this port
