####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX IAM
http:
  routers:
    local_iam_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/iam/`)"
      service: local_iam
      middlewares:
        - local_iam

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_iam:
      stripPrefix:
        prefixes:
          - "/mfe/iam"

  services:
    local_iam:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5029/"   # Angular project started outside Docker with this port
