####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX Parameter
http:
  routers:
    local_parameter_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/parameter/`)"
      service: local_parameter
      middlewares:
        - local_parameter

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_parameter:
      stripPrefix:
        prefixes:
          - "/mfe/parameter"

  services:
    local_parameter:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5030/"   # Angular project started outside Docker with this port
