####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX Product Store
http:
  routers:
    local_product-store_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/product-store/`)"
      service: local_product-store
      middlewares:
        - local_product-store

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_product-store:
      stripPrefix:
        prefixes:
          - "/mfe/product-store"

  services:
    local_product-store:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5021/"   # Angular project started outside Docker with this port
