####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX Theme
http:
  routers:
    local_theme_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/theme/`)"
      service: local_theme
      middlewares:
        - local_theme

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_theme:
      stripPrefix:
        prefixes:
          - "/mfe/theme"

  services:
    local_theme:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5020/"   # Angular project started outside Docker with this port
