####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX User Profile
http:
  routers:
    local_user-profile_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/user-profile/`)"
      service: local_user-profile
      middlewares:
        - local_user-profile

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_user-profile:
      stripPrefix:
        prefixes:
          - "/mfe/user-profile"

  services:
    local_user-profile:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5027/"   # Angular project started outside Docker with this port
