####################################################
# Integrate a local running Microfrontend into OneCX
####################################################
# OneCX Welcome
http:
  routers:
    local_welcome_router:
      # path prefix as used for MFE registration in product store
      rule: "Host(`local-proxy`) && PathPrefix(`/mfe/welcome/`)"
      service: local_welcome
      middlewares:
        - local_welcome

  # Remove the used mfe path so that it maps directly to localhost:port
  middlewares:
    local_welcome:
      stripPrefix:
        prefixes:
          - "/mfe/welcome"

  services:
    local_welcome:
      loadBalancer:
        servers:
        - url: "http://host.docker.internal:5028/"   # Angular project started outside Docker with this port
